<a href="https://colab.research.google.com/github/datasciencejames/datasciencejames.github.io/blob/main/Korea_income_gini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
!pip install tabula-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tabula-py
  Downloading tabula_py-2.6.0-py3-none-any.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 22.7 MB/s
Collecting distro
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from tabula-py) (1.21.6)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.8/dist-packages (from tabula-py) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.25.3->tabula-py) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.8.0 tabula-py-2.6.0

In [3]:
!apt install ghostscript python3-tk

Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-tk is already the newest version (3.6.9-1~18.04).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  fonts-droid-fallback fonts-noto-mono gsfonts libcupsfilters1 libcupsimage2
  libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
Suggested packages:
  fonts-noto ghostscript-x poppler-utils fonts-japanese-mincho
  | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-nanum
The following NEW packages will be installed:
  fonts-droid-fallback fonts-noto-mono ghostscript gsfonts libcupsfilters1
  libcupsimage2 libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
0 upgraded, 11 newly installed, 0 to remove and 11 not upgraded.
Need to get 14.1 MB of archives.
After this operation, 49.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1 [1,805 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 poppler-data all 0.4.8-2 [1,479 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-noto-mono all 20171026-2 [75.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsimage2 amd64 2.2.7-1ubuntu2.9 [18.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libijs-0.35 amd64 0.35-13 [15.5 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libjbig2dec0 amd64 0.13-6 [55.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9-common all 9.26~dfsg+0-0ubuntu0.18.04.17 [5,092 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9 amd64 9.26~dfsg+0-0ubuntu0.18.04.17 [2,267 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 ghostscript amd64 9.26~dfsg+0-0ubuntu0.18.04.17 [51.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4 [3,120 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsfilters1 amd64 1.20.2-0ubuntu3.1 [108 kB]
Fetched 14.1 MB in 1s (12.3 MB/s)
Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 124013 files and directories currently installed.)
Preparing to unpack .../00-fonts-droid-fallback_1%3a6.0.1r16-1.1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../01-poppler-data_0.4.8-2_all.deb ...
Unpacking poppler-data (0.4.8-2) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../02-fonts-noto-mono_20171026-2_all.deb ...
Unpacking fonts-noto-mono (20171026-2) ...
Selecting previously unselected package libcupsimage2:amd64.
Preparing to unpack .../03-libcupsimage2_2.2.7-1ubuntu2.9_amd64.deb ...
Unpacking libcupsimage2:amd64 (2.2.7-1ubuntu2.9) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../04-libijs-0.35_0.35-13_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-13) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../05-libjbig2dec0_0.13-6_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.13-6) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../06-libgs9-common_9.26~dfsg+0-0ubuntu0.18.04.17_all.deb ...
Unpacking libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Selecting previously unselected package libgs9:amd64.
Preparing to unpack .../07-libgs9_9.26~dfsg+0-0ubuntu0.18.04.17_amd64.deb ...
Unpacking libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../08-ghostscript_9.26~dfsg+0-0ubuntu0.18.04.17_amd64.deb ...
Unpacking ghostscript (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Selecting previously unselected package gsfonts.
Preparing to unpack .../09-gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.4_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Selecting previously unselected package libcupsfilters1:amd64.
Preparing to unpack .../10-libcupsfilters1_1.20.2-0ubuntu3.1_amd64.deb ...
Unpacking libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Setting up fonts-droid-fallback (1:6.0.1r16-1.1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Setting up poppler-data (0.4.8-2) ...
Setting up fonts-noto-mono (20171026-2) ...
Setting up libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libcupsimage2:amd64 (2.2.7-1ubuntu2.9) ...
Setting up libjbig2dec0:amd64 (0.13-6) ...
Setting up libijs-0.35:amd64 (0.35-13) ...
Setting up libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Setting up ghostscript (9.26~dfsg+0-0ubuntu0.18.04.17) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for fontconfig (2.12.6-0ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...

In [4]:
from ctypes.util import find_library
find_library("gs")

'libgs.so.9'

In [5]:
!pip install ghostscript

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ghostscript
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.8/dist-packages (from ghostscript) (57.4.0)
Installing collected packages: ghostscript
Successfully installed ghostscript-0.7

In [6]:
!pip install camelot-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting camelot-py
  Downloading camelot_py-0.10.1-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 30 kB/s
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (3.0.10)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (7.1.2)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (0.8.10)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (1.3.5)
Collecting pdfminer.six>=20200726
  Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 35.0 MB/s
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (3.0.4)
Collecting PyPDF2>=1.26.0
  Downloading pypdf2-2.11.2-py3-none-any.whl (220 kB)
     |████████████████████████████████| 220 kB 67.3 MB/s
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.8/dist-packages (from camelot-py) (1.21.6)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.8/dist-packages (from openpyxl>=2.5.8->camelot-py) (1.1.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23.4->camelot-py) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23.4->camelot-py) (2.8.2)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six>=20200726->camelot-py) (2.1.1)
Collecting cryptography>=36.0.0
  Downloading cryptography-38.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 50.1 MB/s
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py) (2.21)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.8/dist-packages (from PyPDF2>=1.26.0->camelot-py) (4.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23.4->camelot-py) (1.15.0)
Installing collected packages: cryptography, PyPDF2, pdfminer.six, camelot-py
Successfully installed PyPDF2-2.11.2 camelot-py-0.10.1 cryptography-38.0.4 pdfminer.six-20221105

In [7]:
!pip install opencv-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.8/dist-packages (from opencv-python) (1.21.6)

In [8]:
import io

In [9]:
import camelot

In [11]:
tables = camelot.read_pdf("Kang (2001).pdf",pages='26')

In [13]:
df1 = tables[0].df

In [16]:
df1

,0,1,2,3,4,5
0,Year,Choo (1992),"Ahn (1992,1995)",Whang & Lee\n(1996),FIES (NSO),Yoo (1998)
1,1965,0.3439,0.3365,,,
2,1966,,0.3287,,,
3,1967,,0.3647,,,
4,1968,,0.3458,,,
5,1969,,0.3464,,,
6,1970,0.3322,0.3125,,,
7,1971,,0.3074,,,
8,1972,,0.3121,,,
9,1973,,0.3676,,,
10,1974,,0.3823,,,
11,1975,,0.3769,,,
12,1976,0.3908,0.3899,,,
13,1977,,0.3780,,,
14,1978,,0.3699,,,
15,1979,,0.3752,,,
16,1980,0.3891,0.3567,,0.3065,0.366
17,1981,,0.3572,,0.3059,
18,1982,0.3574,0.3766,0.393,0.3092,
19,1983,,0.3736,,0.3094,
20,1984,,0.3804,,0.3111,0.351
21,1985,0.3449,0.3803,0.384,0.3115,
22,1986,0.3368,0.3771,,0.3069,0.340
23,1987,,0.3777,,0.3065,
24,1988,0.3355,0.384,0.365,0.3006,0.327
25,1989,,0.4127,,0.3039,
26,1990,0.3226,0.4017,,0.2948,0.300
27,1991,,0.4013,0.365,0.2869,0.302
28,1992,,0.3883,,0.2836,0.287
29,1993,0.3097,0.3797,,0.2817,0.289
30,1994,,0.3845,0.363,0.2845,
31,1995,,,,0.2837,
32,1996,,,,0.2907,0.288
33,1997,,,,0.2830,0.282
34,1998,,,,0.3163,
35,1999,,,,0.3210,
36,2000,,,,0.3207,

In [15]:
df2 = df1.drop(columns={1,3,4,5},axis=0)

In [20]:
df2.head(3)

      0                2
0  Year  Ahn (1992,1995)
1  1965           0.3365
2  1966           0.3287

In [25]:
df3 = df2.drop(df2.index[0])

In [26]:
df4 = df3.rename(columns={0:"year", 2:"gini"})

In [28]:
df4.head(3)

   year    gini
1  1965  0.3365
2  1966  0.3287
3  1967  0.3647

In [29]:
df5 = df4.loc[[1]]

In [30]:
df5

   year    gini
1  1965  0.3365